//
// Generated by Bluespec Compiler, version 2021.07-3-g8227dc97 (build 8227dc97)
//
// On Fri Sep  3 12:08:20 PDT 2021
//
//
// Ports:
// Name                         I/O  size props
// decoder_func_32                O    75
// decoder_func_32_inst           I    32
// decoder_func_32_csrs           I   101
// decoder_func_32_compressed     I     1
//
// Combinational paths from inputs to outputs:
//   (decoder_func_32_inst,
//    decoder_func_32_csrs,
//    decoder_func_32_compressed) -> decoder_func_32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decoder_func_32(decoder_func_32_inst,
			      decoder_func_32_csrs,
			      decoder_func_32_compressed,
			      decoder_func_32);
  // value method decoder_func_32
  input  [31 : 0] decoder_func_32_inst;
  input  [100 : 0] decoder_func_32_csrs;
  input  decoder_func_32_compressed;
  output [74 : 0] decoder_func_32;

  // signals for module outputs
  wire [74 : 0] decoder_func_32;

  // remaining internal signals
  reg [10 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10;
  reg [7 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q11;
  reg [5 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8,
	      _theResult_____8_fst__h2687,
	      _theResult_____8_fst__h2742;
  reg [3 : 0] CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q12,
	      CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14,
	      CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q9,
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265,
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272,
	      IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486,
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293,
	      fn___1__h6119,
	      fn___1__h6167;
  reg [2 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q16;
  reg [1 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q15;
  reg CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q5,
      CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q1,
      CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q4,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7,
      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128,
      IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190,
      IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358,
      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119,
      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132,
      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204,
      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332,
      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d369,
      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255,
      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405;
  wire [47 : 0] IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d497;
  wire [42 : 0] IF_decoder_func_32_inst_BIT_12_95_AND_decoder__ETC___d496;
  wire [31 : 0] immediate_value___1__h3317,
		immediate_value__h48,
		instr_meta_immediate__h987;
  wire [11 : 0] IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d434;
  wire [10 : 0] bit20_30__h46;
  wire [7 : 0] bit12_19__h45;
  wire [6 : 0] instr_meta_funct__h988, temp1___1__h6029, temp1__h77;
  wire [5 : 0] _theResult_____8_fst__h2715, trapcause___1__h2738, x__h6032;
  wire [4 : 0] x__h21, x__h210, x__h456, x__h514;
  wire [3 : 0] IF_NOT_decoder_func_32_inst_BIT_26_38_39_AND_N_ETC___d273,
	       IF_decoder_func_32_csrs_BIT_47_24_AND_decoder__ETC___d269,
	       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d285,
	       IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472,
	       fn___1__h6094,
	       fn___1__h6116;
  wire [2 : 0] IF_decoder_func_32_compressed_THEN_3_ELSE_2___d58;
  wire IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d247,
       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d397,
       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d408,
       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114,
       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157,
       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339,
       IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d201,
       IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d366,
       NOT_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_ETC___d402,
       NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d158,
       NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202,
       address_valid___d245,
       decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171,
       decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121,
       decoder_func_32_inst_BITS_1_TO_0_2_EQ_0b11_3_O_ETC___d411,
       decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228,
       decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_05__ETC___d252,
       decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197,
       decoder_func_32_inst_BIT_26_38_OR_decoder_func_ETC___d340,
       valid_csr_access___d242;

  // value method decoder_func_32
  assign decoder_func_32 =
	     { x__h21,
	       x__h210,
	       x__h456,
	       x__h514,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q15,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q16,
	       decoder_func_32_inst[6:4] == 3'b100,
	       decoder_func_32_inst[6:2] == 5'b00001 ||
	       decoder_func_32_inst[6:4] == 3'b101 &&
	       decoder_func_32_inst[31:28] != 4'b1010 &&
	       decoder_func_32_inst[31:28] != 4'b1100 &&
	       decoder_func_32_inst[31:28] != 4'b1110 ||
	       decoder_func_32_inst[6:4] == 3'b100,
	       IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d497 } ;

  // remaining internal signals
  module_valid_csr_access instance_valid_csr_access_1(.valid_csr_access_csr_addr(decoder_func_32_inst[31:20]),
						      .valid_csr_access_operand(decoder_func_32_inst[19:15]),
						      .valid_csr_access_operation(decoder_func_32_inst[13:12]),
						      .valid_csr_access_tvm(decoder_func_32_csrs[20]),
						      .valid_csr_access_prv(decoder_func_32_csrs[100:99]),
						      .valid_csr_access(valid_csr_access___d242));
  module_address_valid instance_address_valid_0(.address_valid_addr(decoder_func_32_inst[31:20]),
						.address_valid_misa(decoder_func_32_csrs[60:35]),
						.address_valid(address_valid___d245));
  assign IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d497 =
	     { (decoder_func_32_inst[1:0] != 2'b11 &&
		IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255) ?
		 4'd6 :
		 IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293,
	       IF_decoder_func_32_inst_BIT_12_95_AND_decoder__ETC___d496,
	       1'd0 } ;
  assign IF_NOT_decoder_func_32_inst_BIT_26_38_39_AND_N_ETC___d273 =
	     NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d158 ?
	       4'd8 :
	       4'd6 ;
  assign IF_decoder_func_32_compressed_THEN_3_ELSE_2___d58 =
	     decoder_func_32_compressed ? 3'd3 : 3'd2 ;
  assign IF_decoder_func_32_csrs_BIT_47_24_AND_decoder__ETC___d269 =
	     (decoder_func_32_csrs[47] &&
	      decoder_func_32_inst[31:25] == 7'd1) ?
	       4'd9 :
	       (IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128 ?
		  4'd0 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d247 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:7] != 25'd0 &&
	       decoder_func_32_inst[31:7] != 25'h0002000 &&
	       (decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228 ||
		decoder_func_32_inst[31:20] == 12'h105 &&
		decoder_func_32_inst[19:15] == 5'd0 &&
		decoder_func_32_inst[11:7] == 5'd0 &&
		(!decoder_func_32_csrs[21] ||
		 decoder_func_32_csrs[100:99] == 2'd3)) :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d242 &&
	       address_valid___d245 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d285 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 :
	       ((decoder_func_32_inst[14:12] != 3'd4 &&
		 valid_csr_access___d242 &&
		 address_valid___d245) ?
		  4'd5 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d397 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       (decoder_func_32_inst[31:20] != 12'h002 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		!decoder_func_32_csrs[48]) &&
	       (decoder_func_32_inst[31:20] != 12'h302 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		decoder_func_32_csrs[100:99] != 2'd3) &&
	       (decoder_func_32_inst[31:20] != 12'h105 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		decoder_func_32_csrs[21] &&
		decoder_func_32_csrs[100:99] != 2'd3) :
	       decoder_func_32_inst[14:12] == 3'd4 ||
	       !valid_csr_access___d242 ||
	       !address_valid___d245 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d408 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:7] != 25'd0 &&
	       decoder_func_32_inst[31:7] != 25'h0002000 &&
	       decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228 :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d242 &&
	       address_valid___d245 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114 =
	     (decoder_func_32_inst[14:12] == 3'd1) ?
	       decoder_func_32_inst[31:25] == 7'b0 :
	       decoder_func_32_inst[14:12] != 3'd5 ||
	       decoder_func_32_inst[31:25] == 7'b0 ||
	       decoder_func_32_inst[31:25] == 7'b0100000 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] != 3'b101 &&
	       decoder_func_32_csrs[34:32] != 3'b110 &&
	       decoder_func_32_csrs[34:32] != 3'b111 :
	       decoder_func_32_inst[14:12] != 3'd5 &&
	       decoder_func_32_inst[14:12] != 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] == 3'b101 ||
	       decoder_func_32_csrs[34:32] == 3'b110 ||
	       decoder_func_32_csrs[34:32] == 3'b111 :
	       decoder_func_32_inst[14:12] == 3'd5 ||
	       decoder_func_32_inst[14:12] == 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d201 =
	     IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 ||
	     CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q1 ;
  assign IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d366 =
	     IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 &&
	     CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q4 ;
  assign IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d434 =
	     { (decoder_func_32_inst[6:2] == 5'b11000) ?
		 decoder_func_32_inst[7] :
		 decoder_func_32_inst[6:2] != 5'b01101 &&
		 decoder_func_32_inst[6:2] != 5'b00101 &&
		 ((decoder_func_32_inst[6:2] == 5'b11011) ?
		    decoder_func_32_inst[20] :
		    decoder_func_32_inst[31]),
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8,
	       (decoder_func_32_inst[6:2] == 5'b01000 ||
		decoder_func_32_inst[6:2] == 5'b01001 &&
		decoder_func_32_csrs[40] ||
		decoder_func_32_inst[6:2] == 5'b11000) ?
		 decoder_func_32_inst[11:8] :
		 CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q9,
	       (decoder_func_32_inst[6:2] == 5'b01000 ||
		decoder_func_32_inst[6:2] == 5'b01001 &&
		decoder_func_32_csrs[40]) ?
		 decoder_func_32_inst[7] :
		 decoder_func_32_inst[6:2] != 5'b11000 &&
		 decoder_func_32_inst[6:2] != 5'b01101 &&
		 decoder_func_32_inst[6:2] != 5'b00101 &&
		 decoder_func_32_inst[6:2] != 5'b11011 &&
		 decoder_func_32_inst[20] } ;
  assign IF_decoder_func_32_inst_BIT_12_95_AND_decoder__ETC___d496 =
	     { (decoder_func_32_inst[12] &&
		decoder_func_32_inst[6:2] == 5'b00011) ?
		 3'd4 :
		 ((!decoder_func_32_inst[12] &&
		   decoder_func_32_inst[6:2] == 5'b00011) ?
		    3'd3 :
		    ((decoder_func_32_inst[6:2] == 5'b01000 ||
		      decoder_func_32_inst[6:2] == 5'b01001 &&
		      decoder_func_32_csrs[40]) ?
		       3'd1 :
		       3'd0)),
	       instr_meta_immediate__h987,
	       instr_meta_funct__h988,
	       decoder_func_32_inst[6:2] == 5'b00011 ||
	       decoder_func_32_inst_BITS_1_TO_0_2_EQ_0b11_3_O_ETC___d411 } ;
  assign IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472 =
	     decoder_func_32_inst[30] ? 4'b1011 : 4'b0101 ;
  assign NOT_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_ETC___d402 =
	     decoder_func_32_inst[6:5] != 2'b11 ||
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 ;
  assign NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d158 =
	     !decoder_func_32_inst[26] &&
	     decoder_func_32_csrs[14:13] != 2'd0 &&
	     !decoder_func_32_inst[25] &&
	     decoder_func_32_csrs[40] &&
	     IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157 ;
  assign NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202 =
	     !decoder_func_32_inst[26] &&
	     decoder_func_32_csrs[14:13] != 2'd0 &&
	     !decoder_func_32_inst[25] &&
	     decoder_func_32_csrs[40] &&
	     IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d201 ;
  assign _theResult_____8_fst__h2715 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       _theResult_____8_fst__h2742 :
	       6'd2 ;
  assign bit12_19__h45 = {8{decoder_func_32_inst[31]}} ;
  assign bit20_30__h46 =
	     { bit12_19__h45,
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31] } ;
  assign decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171 =
	     decoder_func_32_inst[14:12] < 3'd2 ;
  assign decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 =
	     decoder_func_32_inst[14:12] < 3'd3 ;
  assign decoder_func_32_inst_BITS_1_TO_0_2_EQ_0b11_3_O_ETC___d411 =
	     (decoder_func_32_inst[1:0] == 2'b11 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405) &&
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     decoder_func_32_inst[4:2] == 3'b100 &&
	     IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d408 ;
  assign decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228 =
	     decoder_func_32_inst[31:20] == 12'h002 &&
	     decoder_func_32_inst[19:15] == 5'd0 &&
	     decoder_func_32_inst[11:7] == 5'd0 &&
	     decoder_func_32_csrs[48] ||
	     decoder_func_32_inst[31:20] == 12'h302 &&
	     decoder_func_32_inst[19:15] == 5'd0 &&
	     decoder_func_32_inst[11:7] == 5'd0 &&
	     decoder_func_32_csrs[100:99] == 2'd3 ;
  assign decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_05__ETC___d252 =
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 ;
  assign decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197 =
	     decoder_func_32_inst[25] == ~decoder_func_32_inst[20] ;
  assign decoder_func_32_inst_BIT_26_38_OR_decoder_func_ETC___d340 =
	     decoder_func_32_inst[26] ||
	     decoder_func_32_csrs[14:13] == 2'd0 ||
	     decoder_func_32_inst[25] ||
	     !decoder_func_32_csrs[40] ||
	     IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339 ;
  assign fn___1__h6094 = { 3'd1, decoder_func_32_inst[12] } ;
  assign fn___1__h6116 = { 1'b1, decoder_func_32_inst[14:12] } ;
  assign immediate_value___1__h3317 =
	     { 15'd0,
	       decoder_func_32_inst[19:15],
	       IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d434 } ;
  assign immediate_value__h48 =
	     { decoder_func_32_inst[31],
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q11,
	       IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d434 } ;
  assign instr_meta_funct__h988 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405) ?
	       temp1___1__h6029 :
	       temp1__h77 ;
  assign instr_meta_immediate__h987 =
	     decoder_func_32_inst_BITS_1_TO_0_2_EQ_0b11_3_O_ETC___d411 ?
	       immediate_value___1__h3317 :
	       immediate_value__h48 ;
  assign temp1___1__h6029 = { 1'd0, x__h6032 } ;
  assign temp1__h77 =
	     { IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486,
	       ((decoder_func_32_inst[1:0] == 2'b11 ||
		 IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405) &&
		decoder_func_32_inst[6:5] == 2'b10 &&
		IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204 &&
		decoder_func_32_inst[14:12] == 3'd7) ?
		 decoder_func_32_csrs[34:32] :
		 decoder_func_32_inst[14:12] } ;
  assign trapcause___1__h2738 =
	     (decoder_func_32_csrs[55] &&
	      decoder_func_32_csrs[100:99] == 2'd0) ?
	       6'd8 :
	       6'd11 ;
  assign x__h21 =
	     (decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:2] == 5'b00101 ||
	      decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14]) ?
	       5'd0 :
	       decoder_func_32_inst[19:15] ;
  assign x__h210 =
	     (decoder_func_32_inst[6:2] == 5'b11100 ||
	      decoder_func_32_inst[6:4] == 3'b0 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:4] == 3'b001 ||
	      decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b11001 ||
	      decoder_func_32_inst[6:4] == 3'b101 &&
	      decoder_func_32_inst[30] &&
	      decoder_func_32_csrs[38] | decoder_func_32_csrs[40]) ?
	       5'd0 :
	       decoder_func_32_inst[24:20] ;
  assign x__h456 =
	     (decoder_func_32_inst[6:2] == 5'b11000 ||
	      decoder_func_32_inst[6:3] == 4'b0100 ||
	      decoder_func_32_inst[6:2] == 5'b00011) ?
	       5'd0 :
	       decoder_func_32_inst[11:7] ;
  assign x__h514 =
	     (decoder_func_32_inst[6:4] == 3'b100) ?
	       decoder_func_32_inst[31:27] :
	       5'd0 ;
  assign x__h6032 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 ||
	      decoder_func_32_inst[6:5] == 2'b0 ||
	      decoder_func_32_inst[6:5] == 2'b01 ||
	      decoder_func_32_inst[6:5] == 2'b10) ?
	       6'd2 :
	       ((decoder_func_32_inst[6:5] == 2'b11) ?
		  _theResult_____8_fst__h2687 :
		  6'd2) ;
  always@(decoder_func_32_inst or trapcause___1__h2738)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0: _theResult_____8_fst__h2742 = trapcause___1__h2738;
      25'h0002000: _theResult_____8_fst__h2742 = 6'd3;
      default: _theResult_____8_fst__h2742 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst or _theResult_____8_fst__h2715)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b011: _theResult_____8_fst__h2687 = 6'd2;
      3'b100: _theResult_____8_fst__h2687 = _theResult_____8_fst__h2715;
      default: _theResult_____8_fst__h2687 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128 =
	      decoder_func_32_inst[31:25] == 7'b0 ||
	      decoder_func_32_inst[31:25] == 7'b0100000;
      default: IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128 =
		   decoder_func_32_inst[31:25] == 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157 or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      decoder_func_32_inst[24:21] == 4'b0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       decoder_func_32_inst[14:12] == 3'd1);
      default: IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d190 =
		   decoder_func_32_inst[31:27] == 5'b11110 &&
		   decoder_func_32_inst[24:20] == 5'd0 &&
		   decoder_func_32_inst[14:12] == 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157 or
	  decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q1 =
	      decoder_func_32_inst[24:21] == 4'b0001 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157;
      default: CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q1 =
		   decoder_func_32_inst[31:27] == 5'b01000 &&
		   decoder_func_32_inst[24:21] == 4'b0 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d157 &&
		   decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228 or
	  decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0, 25'h0002000:
	  CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 = 4'd6;
      default: CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 =
		   decoder_func_32_inst_BITS_31_TO_20_14_EQ_0x2_1_ETC___d228 ?
		     4'd5 :
		     ((decoder_func_32_inst[31:20] == 12'h105 &&
		       decoder_func_32_inst[19:15] == 5'd0 &&
		       decoder_func_32_inst[11:7] == 5'd0) ?
			((!decoder_func_32_csrs[21] ||
			  decoder_func_32_csrs[100:99] == 2'd3) ?
			   4'd7 :
			   4'd6) :
			4'd6);
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 =
	      decoder_func_32_inst[14:12] != 3'd3 &&
	      decoder_func_32_inst[14:12] != 3'd7;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 =
	      decoder_func_32_csrs[14:13] != 2'd0 &&
	      decoder_func_32_csrs[40] &&
	      decoder_func_32_inst[14:12] == 3'd2;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 =
	      decoder_func_32_inst[14:12] == 3'd0 ||
	      decoder_func_32_inst[14:12] == 3'd1;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 =
		   decoder_func_32_inst[4:2] == 3'b101;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132 =
	      decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132 =
	      decoder_func_32_csrs[40] &&
	      decoder_func_32_csrs[14:13] != 2'd0 &&
	      decoder_func_32_inst[14:12] == 3'd2;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132 =
	      decoder_func_32_csrs[47] &&
	      decoder_func_32_inst[31:25] == 7'd1 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d128;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132 =
		   decoder_func_32_inst[4:2] == 3'b101;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202 or
	  NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d158)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204 =
	      NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d158;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204 =
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d247)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
	      decoder_func_32_inst[14:12] != 3'd2 &&
	      decoder_func_32_inst[14:12] != 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
	      decoder_func_32_inst[14:12] == 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
		   decoder_func_32_inst[4:2] == 3'b011 ||
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d247;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_05__ETC___d252 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d119;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d132;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d204;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d255 =
	      decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_05__ETC___d252;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339 or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      !decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      !decoder_func_32_inst_BITS_14_TO_12_9_ULT_2___d171;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      decoder_func_32_inst[24:21] != 4'b0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d358 =
		   decoder_func_32_inst[31:27] != 5'b11110 ||
		   decoder_func_32_inst[24:20] != 5'd0 ||
		   decoder_func_32_inst[14:12] != 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339 or
	  decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q4 =
	      decoder_func_32_inst[24:21] != 4'b0001 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339;
      default: CASE_decoder_func_32_inst_BITS_31_TO_27_0b1100_ETC__q4 =
		   decoder_func_32_inst[31:27] != 5'b01000 ||
		   decoder_func_32_inst[24:21] != 4'b0 ||
		   IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_7_2_ETC___d339 ||
		   !decoder_func_32_inst_BIT_25_40_EQ_INV_decoder__ETC___d197;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d366 or
	  decoder_func_32_inst_BIT_26_38_OR_decoder_func_ETC___d340)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d369 =
	      decoder_func_32_inst_BIT_26_38_OR_decoder_func_ETC___d340;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d369 =
		   decoder_func_32_inst[4:2] != 3'b100 ||
		   decoder_func_32_inst[26] ||
		   decoder_func_32_csrs[14:13] == 2'd0 ||
		   decoder_func_32_inst[25] ||
		   !decoder_func_32_csrs[40] ||
		   IF_decoder_func_32_inst_BITS_31_TO_27_1_EQ_0b0_ETC___d366;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q5 =
	      decoder_func_32_inst[31:25] != 7'b0 &&
	      decoder_func_32_inst[31:25] != 7'b0100000;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q5 =
		   decoder_func_32_inst[31:25] != 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q5)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332 =
	      !decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332 =
	      !decoder_func_32_csrs[40] ||
	      decoder_func_32_csrs[14:13] == 2'd0 ||
	      decoder_func_32_inst[14:12] != 3'd2;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332 =
	      (!decoder_func_32_csrs[47] ||
	       decoder_func_32_inst[31:25] != 7'd1) &&
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q5;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332 =
		   decoder_func_32_inst[4:2] != 3'b101;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d397)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_inst[14:12] == 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      decoder_func_32_inst[14:12] != 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
		   decoder_func_32_inst[4:2] != 3'b011 &&
		   (decoder_func_32_inst[4:2] != 3'b100 ||
		    IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d397);
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 =
	      decoder_func_32_inst[14:12] == 3'd3 ||
	      decoder_func_32_inst[14:12] == 3'd7;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 =
	      decoder_func_32_csrs[14:13] == 2'd0 ||
	      !decoder_func_32_csrs[40] ||
	      decoder_func_32_inst[14:12] != 3'd2;
      3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 =
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 =
	      (decoder_func_32_inst[14:12] == 3'd1) ?
		decoder_func_32_inst[31:25] != 7'b0 :
		decoder_func_32_inst[14:12] == 3'd5 &&
		decoder_func_32_inst[31:25] != 7'b0 &&
		decoder_func_32_inst[31:25] != 7'b0100000;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 =
		   decoder_func_32_inst[4:2] != 3'b101;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_ETC___d402 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d369)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q7;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d332;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d369;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d405 =
	      NOT_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b11_ETC___d402;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 = 6'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 =
		   decoder_func_32_inst[30:25];
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q9 = 4'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q9 =
		   decoder_func_32_inst[24:21];
    endcase
  end
  always@(decoder_func_32_inst or bit20_30__h46)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
	      decoder_func_32_inst[30:20];
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
		   bit20_30__h46;
    endcase
  end
  always@(decoder_func_32_inst or bit12_19__h45)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q11 =
	      decoder_func_32_inst[19:12];
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q11 =
		   bit12_19__h45;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472)
  begin
    case (decoder_func_32_inst[14:12])
      3'd2: fn___1__h6119 = 4'b1100;
      3'd3: fn___1__h6119 = 4'b1110;
      3'd5:
	  fn___1__h6119 =
	      IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472;
      default: fn___1__h6119 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0: fn___1__h6167 = decoder_func_32_inst[30] ? 4'b1010 : 4'b0;
      3'd2: fn___1__h6167 = 4'b1100;
      3'd3: fn___1__h6167 = 4'b1110;
      3'd5:
	  fn___1__h6167 =
	      IF_decoder_func_32_inst_BIT_30_3_THEN_0b1011_E_ETC___d472;
      default: fn___1__h6167 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  fn___1__h6119 or fn___1__h6167 or fn___1__h6116 or fn___1__h6094)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00100:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486 =
	      fn___1__h6119;
      5'b01100:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486 =
	      fn___1__h6167;
      5'b11000:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486 =
	      decoder_func_32_inst[14] ? fn___1__h6116 : fn___1__h6094;
      default: IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d486 =
		   (decoder_func_32_inst[6:5] == 2'b10 &&
		    decoder_func_32_csrs[40] | decoder_func_32_csrs[38]) ?
		     decoder_func_32_inst[5:2] :
		     4'd0;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd1:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q12 = 4'd1;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q12 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q12 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 =
	      (decoder_func_32_inst[14:12] != 3'd3 &&
	       decoder_func_32_inst[14:12] != 3'd7) ?
		4'd1 :
		4'd6;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 =
	      (decoder_func_32_csrs[14:13] != 2'd0 &&
	       decoder_func_32_csrs[40] &&
	       decoder_func_32_inst[14:12] == 3'd2) ?
		4'd1 :
		4'd6;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 =
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q12;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_1_0_ETC___d114 ?
		4'd0 :
		4'd6;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 = 4'd0;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_csrs_BIT_47_24_AND_decoder__ETC___d269)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 =
	      decoder_func_32_inst_BITS_14_TO_12_9_ULT_3___d121 ? 4'd1 : 4'd6;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 =
	      (decoder_func_32_csrs[40] &&
	       decoder_func_32_csrs[14:13] != 2'd0 &&
	       decoder_func_32_inst[14:12] == 3'd2) ?
		4'd1 :
		4'd6;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 =
	      IF_decoder_func_32_csrs_BIT_47_24_AND_decoder__ETC___d269;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 = 4'd0;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_NOT_decoder_func_32_inst_BIT_26_38_39_AND_N_ETC___d273 or
	  NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 =
	      IF_NOT_decoder_func_32_inst_BIT_26_38_39_AND_N_ETC___d273;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 =
	      NOT_decoder_func_32_inst_BIT_26_38_39_AND_NOT__ETC___d202 ?
		4'd8 :
		4'd6;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d285)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14 =
	      (decoder_func_32_inst[14:12] != 3'd2 &&
	       decoder_func_32_inst[14:12] != 3'd3) ?
		4'd2 :
		4'd6;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14 =
	      (decoder_func_32_inst[14:12] == 3'd0) ? 4'd4 : 4'd6;
      3'b011: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14 = 4'd3;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_0_ETC___d285;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d265;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_7_EQ_0b0_8_ETC___d272;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13;
      2'b11:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d293 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q14;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b11001, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q15 = 2'd1;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q15 =
		   (decoder_func_32_inst[6:4] == 3'b100 ||
		    decoder_func_32_inst[6:4] == 3'b101 &&
		    decoder_func_32_inst[31:28] != 4'b1101 &&
		    decoder_func_32_inst[31:28] != 4'b1111) ?
		     2'd2 :
		     2'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_compressed_THEN_3_ELSE_2___d58)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00011, 5'b11001, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q16 =
	      IF_decoder_func_32_compressed_THEN_3_ELSE_2___d58;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q16 =
		   (decoder_func_32_inst[6:4] == 3'b001 ||
		    decoder_func_32_inst[6:2] == 5'b01101) ?
		     3'd1 :
		     ((decoder_func_32_inst[6:4] == 3'b101 &&
		       !decoder_func_32_inst[30] ||
		       decoder_func_32_inst[6:2] == 5'b01001 ||
		       decoder_func_32_inst[6:4] == 3'b100) ?
			3'd4 :
			3'd0);
    endcase
  end
endmodule  // module_decoder_func_32

