//
// Generated by Bluespec Compiler, version 2021.07-3-g8227dc97 (build 8227dc97)
//
// On Fri Sep  3 12:08:15 PDT 2021
//
//
// Ports:
// Name                         I/O  size props
// fn_single_div                  O    65
// fn_single_div_remainder        I    33
// fn_single_div_quotient         I    32
// fn_single_div_divisor          I    32
//
// Combinational paths from inputs to outputs:
//   (fn_single_div_remainder,
//    fn_single_div_quotient,
//    fn_single_div_divisor) -> fn_single_div
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_single_div(fn_single_div_remainder,
			    fn_single_div_quotient,
			    fn_single_div_divisor,
			    fn_single_div);
  // value method fn_single_div
  input  [32 : 0] fn_single_div_remainder;
  input  [31 : 0] fn_single_div_quotient;
  input  [31 : 0] fn_single_div_divisor;
  output [64 : 0] fn_single_div;

  // signals for module outputs
  wire [64 : 0] fn_single_div;

  // remaining internal signals
  wire [32 : 0] remainder__h61, sub__h63, x__h24;
  wire [31 : 0] x__h100, x__h95;
  wire fn_single_div_remainder_BITS_30_TO_0_CONCAT_fn_ETC___d4;

  // value method fn_single_div
  assign fn_single_div = { x__h24, x__h100 } ;

  // remaining internal signals
  assign fn_single_div_remainder_BITS_30_TO_0_CONCAT_fn_ETC___d4 =
	     { fn_single_div_remainder[30:0], fn_single_div_quotient[31] } <
	     fn_single_div_divisor ;
  assign remainder__h61 =
	     { fn_single_div_remainder[31:0], fn_single_div_quotient[31] } ;
  assign sub__h63 = remainder__h61 + { x__h95[31], x__h95 } ;
  assign x__h100 =
	     { fn_single_div_quotient[30:0],
	       !fn_single_div_remainder_BITS_30_TO_0_CONCAT_fn_ETC___d4 } ;
  assign x__h24 =
	     fn_single_div_remainder_BITS_30_TO_0_CONCAT_fn_ETC___d4 ?
	       remainder__h61 :
	       sub__h63 ;
  assign x__h95 = ~fn_single_div_divisor + 32'd1 ;
endmodule  // module_fn_single_div

