//
// Generated by Bluespec Compiler, version 2021.07-3-g8227dc97 (build 8227dc97)
//
// On Fri Sep  3 12:08:37 PDT 2021
//
//
// Ports:
// Name                         I/O  size props
// fn_csr_op                      O    32
// fn_csr_op_writedata            I    32
// fn_csr_op_readdata             I    32
// fn_csr_op_op                   I     2
//
// Combinational paths from inputs to outputs:
//   (fn_csr_op_writedata, fn_csr_op_readdata, fn_csr_op_op) -> fn_csr_op
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_csr_op(fn_csr_op_writedata,
			fn_csr_op_readdata,
			fn_csr_op_op,
			fn_csr_op);
  // value method fn_csr_op
  input  [31 : 0] fn_csr_op_writedata;
  input  [31 : 0] fn_csr_op_readdata;
  input  [1 : 0] fn_csr_op_op;
  output [31 : 0] fn_csr_op;

  // signals for module outputs
  reg [31 : 0] fn_csr_op;

  // remaining internal signals
  wire [31 : 0] x__h48;

  // value method fn_csr_op
  always@(fn_csr_op_op or x__h48 or fn_csr_op_readdata or fn_csr_op_writedata)
  begin
    case (fn_csr_op_op)
      2'd1: fn_csr_op = fn_csr_op_writedata;
      2'd2: fn_csr_op = fn_csr_op_writedata | fn_csr_op_readdata;
      default: fn_csr_op = x__h48 & fn_csr_op_readdata;
    endcase
  end

  // remaining internal signals
  assign x__h48 = ~fn_csr_op_writedata ;
endmodule  // module_fn_csr_op

